# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Programming Projects\Python\YMCA-Inventory\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(841, 729)
        Dialog.setStyleSheet("#dialogBtn QPushButton{\n"
"background-color: rgb(255, 0, 0);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("\n"
"background-color:rgb(143, 143, 143);\n"
"border-radius: 10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setMouseTracking(True)
        self.widget.setObjectName("widget")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(400, 90, 391, 611))
        self.widget_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:20px;")
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(70, 50, 51, 41))
        self.label.setStyleSheet("background:transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Icons/Icons/log-in.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color: white;\n"
"border-radius:5px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.loginUsername = QtWidgets.QLineEdit(self.widget_3)
        self.loginUsername.setGeometry(QtCore.QRect(50, 150, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.loginUsername.setFont(font)
        self.loginUsername.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-radius:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;\n"
"")
        self.loginUsername.setObjectName("loginUsername")
        self.loginPassword = QtWidgets.QLineEdit(self.widget_3)
        self.loginPassword.setGeometry(QtCore.QRect(50, 240, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.loginPassword.setFont(font)
        self.loginPassword.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-radius:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;\n"
"")
        self.loginPassword.setObjectName("loginPassword")
        self.loginBtn = QtWidgets.QPushButton(self.widget_3)
        self.loginBtn.setGeometry(QtCore.QRect(70, 380, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.loginBtn.setFont(font)
        self.loginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginBtn.setStyleSheet("QPushButton#loginBtn{\n"
"background-color: qlineargradient(spread:pad,  x1:0 y1:0, x2:1 y2:0, stop:0 rgba(184,20,27,1), stop:1 rgba(0,0,0,1));\n"
"color:rgba(255,255,255,230);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#loginBtn:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(22,20,20,1),stop:1  rgba(233,7,15,1));\n"
"color:rgba(255,255,255,230);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#loginBtn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105,118,132,200);\n"
"}")
        self.loginBtn.setObjectName("loginBtn")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(70, 520, 261, 21))
        self.label_3.setStyleSheet("color: #fff;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(140, 550, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:red;\n"
"background:transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(110, 550, 31, 31))
        self.label_4.setStyleSheet("background:transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Icons/Icons/phone-forwarded.svg"))
        self.label_4.setObjectName("label_4")
        self.txtLoginError = QtWidgets.QLabel(self.widget_3)
        self.txtLoginError.setGeometry(QtCore.QRect(40, 120, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.txtLoginError.setFont(font)
        self.txtLoginError.setStyleSheet("color: rgb(223, 0, 0);\n"
"background-color:transparent;")
        self.txtLoginError.setText("")
        self.txtLoginError.setAlignment(QtCore.Qt.AlignCenter)
        self.txtLoginError.setObjectName("txtLoginError")
        self.txtUserError = QtWidgets.QLabel(self.widget_3)
        self.txtUserError.setGeometry(QtCore.QRect(350, 190, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtUserError.setFont(font)
        self.txtUserError.setStyleSheet("background-color:transparent;\n"
"color:red;")
        self.txtUserError.setAlignment(QtCore.Qt.AlignCenter)
        self.txtUserError.setObjectName("txtUserError")
        self.txtPasswordError = QtWidgets.QLabel(self.widget_3)
        self.txtPasswordError.setGeometry(QtCore.QRect(350, 280, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtPasswordError.setFont(font)
        self.txtPasswordError.setStyleSheet("#txtPasswordError{\n"
"color:red;\n"
"background-color:transparent;\n"
"}")
        self.txtPasswordError.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPasswordError.setObjectName("txtPasswordError")
        self.label_2.raise_()
        self.loginUsername.raise_()
        self.loginPassword.raise_()
        self.loginBtn.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.txtLoginError.raise_()
        self.txtUserError.raise_()
        self.txtPasswordError.raise_()
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(20, 220, 351, 141))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Images/Images/Yamaha-WaterMark-lessopacity.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.headerLogin = QtWidgets.QWidget(self.widget)
        self.headerLogin.setGeometry(QtCore.QRect(0, 0, 821, 71))
        self.headerLogin.setStyleSheet("background-color:#2c313c;")
        self.headerLogin.setObjectName("headerLogin")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.headerLogin)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.headerLogin)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setMinimumSize(QtCore.QSize(35, 35))
        self.label_9.setMaximumSize(QtCore.QSize(35, 35))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/Images/Images/Yamaha-Logo.ico"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:red;")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.headerLogin)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(499, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame_3)
        self.dialogBtn = QtWidgets.QFrame(self.headerLogin)
        self.dialogBtn.setStyleSheet("#closeWindowsBtn:hover{\n"
"background-color:red;\n"
"\n"
"}\n"
"#minimizeWindowsBtn:hover,#restoreWindowsBtn:hover{\n"
"background-color: #24262b;\n"
"}")
        self.dialogBtn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dialogBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dialogBtn.setObjectName("dialogBtn")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dialogBtn)
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimizeWindowsBtn = QtWidgets.QPushButton(self.dialogBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizeWindowsBtn.sizePolicy().hasHeightForWidth())
        self.minimizeWindowsBtn.setSizePolicy(sizePolicy)
        self.minimizeWindowsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeWindowsBtn.setStyleSheet("border-radius:none;")
        self.minimizeWindowsBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeWindowsBtn.setIcon(icon)
        self.minimizeWindowsBtn.setObjectName("minimizeWindowsBtn")
        self.horizontalLayout_4.addWidget(self.minimizeWindowsBtn)
        self.restoreWindowsBtn = QtWidgets.QPushButton(self.dialogBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restoreWindowsBtn.sizePolicy().hasHeightForWidth())
        self.restoreWindowsBtn.setSizePolicy(sizePolicy)
        self.restoreWindowsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restoreWindowsBtn.setStyleSheet("border-radius:none;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreWindowsBtn.setIcon(icon1)
        self.restoreWindowsBtn.setObjectName("restoreWindowsBtn")
        self.horizontalLayout_4.addWidget(self.restoreWindowsBtn)
        self.closeWindowsBtn = QtWidgets.QPushButton(self.dialogBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeWindowsBtn.sizePolicy().hasHeightForWidth())
        self.closeWindowsBtn.setSizePolicy(sizePolicy)
        self.closeWindowsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeWindowsBtn.setStyleSheet("border-radius:none;")
        self.closeWindowsBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeWindowsBtn.setIcon(icon2)
        self.closeWindowsBtn.setObjectName("closeWindowsBtn")
        self.horizontalLayout_4.addWidget(self.closeWindowsBtn)
        self.horizontalLayout.addWidget(self.dialogBtn)
        self.txtDatabaseconnection = QtWidgets.QLabel(self.widget)
        self.txtDatabaseconnection.setGeometry(QtCore.QRect(20, 680, 251, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtDatabaseconnection.setFont(font)
        self.txtDatabaseconnection.setStyleSheet("color:#2c313c;")
        self.txtDatabaseconnection.setText("")
        self.txtDatabaseconnection.setObjectName("txtDatabaseconnection")
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "LOG IN"))
        self.loginUsername.setPlaceholderText(_translate("Dialog", "User Name"))
        self.loginPassword.setPlaceholderText(_translate("Dialog", "Password"))
        self.loginBtn.setText(_translate("Dialog", "Log In"))
        self.label_3.setText(_translate("Dialog", "Forgot your User Name | Password ?"))
        self.label_5.setText(_translate("Dialog", "YMCA - IT Service Desk"))
        self.txtUserError.setText(_translate("Dialog", "X"))
        self.txtPasswordError.setText(_translate("Dialog", "X"))
        self.label_10.setText(_translate("Dialog", "YMCA INVENTORY "))
        self.minimizeWindowsBtn.setToolTip(_translate("Dialog", "Minimize Window"))
        self.restoreWindowsBtn.setToolTip(_translate("Dialog", "Restore Window"))
        self.closeWindowsBtn.setToolTip(_translate("Dialog", "Close Window"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
